Resources:
  sendEmailHandlerServiceRoleD7E87A67:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: DiamondfinishesBackendStack/sendEmailHandler/ServiceRole/Resource
  sendEmailHandlerA44844D3:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 98b7285d49332c4dc185461a415d3f29ca72c61904692e440b0116c49f411492.zip
      Role:
        Fn::GetAtt:
          - sendEmailHandlerServiceRoleD7E87A67
          - Arn
      Description: handles sending emails to user
      FunctionName: sendEmailHandler
      Handler: sendEmail.handler
      Runtime: nodejs12.x
    DependsOn:
      - sendEmailHandlerServiceRoleD7E87A67
    Metadata:
      aws:cdk:path: DiamondfinishesBackendStack/sendEmailHandler/Resource
      aws:asset:path: asset.98b7285d49332c4dc185461a415d3f29ca72c61904692e440b0116c49f411492
      aws:asset:is-bundled: false
      aws:asset:property: Code
  DiamondFinishesAPI2DEAC26E:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: API Gateway for Diamond Finishes
      Name: Diamond Finishes API
    Metadata:
      aws:cdk:path: DiamondfinishesBackendStack/DiamondFinishesAPI/Resource
  DiamondFinishesAPICloudWatchRoleA7CDECBA:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: DiamondfinishesBackendStack/DiamondFinishesAPI/CloudWatchRole/Resource
  DiamondFinishesAPIAccount87D50414:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - DiamondFinishesAPICloudWatchRoleA7CDECBA
          - Arn
    DependsOn:
      - DiamondFinishesAPI2DEAC26E
    Metadata:
      aws:cdk:path: DiamondfinishesBackendStack/DiamondFinishesAPI/Account
  DiamondFinishesAPIDeployment9B35F797333e786c8c5580e6cb0e30381b510a1a:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: DiamondFinishesAPI2DEAC26E
      Description: Automatically created by the RestApi construct
    DependsOn:
      - DiamondFinishesAPIproxyANY42CB169E
      - DiamondFinishesAPIproxy9AD4ED05
      - DiamondFinishesAPIANY259AB345
    Metadata:
      aws:cdk:path: DiamondfinishesBackendStack/DiamondFinishesAPI/Deployment/Resource
  DiamondFinishesAPIDeploymentStageprod6E0DB9B4:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: DiamondFinishesAPI2DEAC26E
      DeploymentId:
        Ref: DiamondFinishesAPIDeployment9B35F797333e786c8c5580e6cb0e30381b510a1a
      StageName: prod
    DependsOn:
      - DiamondFinishesAPIAccount87D50414
    Metadata:
      aws:cdk:path: DiamondfinishesBackendStack/DiamondFinishesAPI/DeploymentStage.prod/Resource
  DiamondFinishesAPIproxy9AD4ED05:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - DiamondFinishesAPI2DEAC26E
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: DiamondFinishesAPI2DEAC26E
    Metadata:
      aws:cdk:path: DiamondfinishesBackendStack/DiamondFinishesAPI/Default/{proxy+}/Resource
  DiamondFinishesAPIproxyANYApiPermissionDiamondfinishesBackendStackDiamondFinishesAPI24FD4D4EANYproxyC7F3B570:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - sendEmailHandlerA44844D3
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: DiamondFinishesAPI2DEAC26E
            - /
            - Ref: DiamondFinishesAPIDeploymentStageprod6E0DB9B4
            - /*/*
    Metadata:
      aws:cdk:path: DiamondfinishesBackendStack/DiamondFinishesAPI/Default/{proxy+}/ANY/ApiPermission.DiamondfinishesBackendStackDiamondFinishesAPI24FD4D4E.ANY..{proxy+}
  DiamondFinishesAPIproxyANYApiPermissionTestDiamondfinishesBackendStackDiamondFinishesAPI24FD4D4EANYproxy865FDB4D:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - sendEmailHandlerA44844D3
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: DiamondFinishesAPI2DEAC26E
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: DiamondfinishesBackendStack/DiamondFinishesAPI/Default/{proxy+}/ANY/ApiPermission.Test.DiamondfinishesBackendStackDiamondFinishesAPI24FD4D4E.ANY..{proxy+}
  DiamondFinishesAPIproxyANY42CB169E:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Ref: DiamondFinishesAPIproxy9AD4ED05
      RestApiId:
        Ref: DiamondFinishesAPI2DEAC26E
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - sendEmailHandlerA44844D3
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: DiamondfinishesBackendStack/DiamondFinishesAPI/Default/{proxy+}/ANY/Resource
  DiamondFinishesAPIANYApiPermissionDiamondfinishesBackendStackDiamondFinishesAPI24FD4D4EANYCE060A1A:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - sendEmailHandlerA44844D3
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: DiamondFinishesAPI2DEAC26E
            - /
            - Ref: DiamondFinishesAPIDeploymentStageprod6E0DB9B4
            - /*/
    Metadata:
      aws:cdk:path: DiamondfinishesBackendStack/DiamondFinishesAPI/Default/ANY/ApiPermission.DiamondfinishesBackendStackDiamondFinishesAPI24FD4D4E.ANY..
  DiamondFinishesAPIANYApiPermissionTestDiamondfinishesBackendStackDiamondFinishesAPI24FD4D4EANYE0C4393C:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - sendEmailHandlerA44844D3
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: DiamondFinishesAPI2DEAC26E
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: DiamondfinishesBackendStack/DiamondFinishesAPI/Default/ANY/ApiPermission.Test.DiamondfinishesBackendStackDiamondFinishesAPI24FD4D4E.ANY..
  DiamondFinishesAPIANY259AB345:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: ANY
      ResourceId:
        Fn::GetAtt:
          - DiamondFinishesAPI2DEAC26E
          - RootResourceId
      RestApiId:
        Ref: DiamondFinishesAPI2DEAC26E
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - sendEmailHandlerA44844D3
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: DiamondfinishesBackendStack/DiamondFinishesAPI/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1WQ0U7DMAxFv4X31DAmxHM3tCemTeUDpiw1xWuTVLXDqKr+O0kKYjz53GvZ18kjrJ7g4U5fuTB1W3R0hulNtGlVtE5Tp+251jDtgjNC3qntu7vlIw6WmKOaFWkLU+U7TI1UZ8Xrk2ZGYShTiRo2wbQoG82odE+NFrzqEabXHFQhS9lTXvCHpTE+OFEv2Hd+tBgxujcqHtzk1AXiqA+DwRxyHPzX+Ov8LF54j/Lh62QtNM8qX5mWkGtS4xCkD/JvKvLWu5okv9n5GuHC95+rZ1jHf7wwUTHEY8kiVEv9BgtoagdjAQAA
    Metadata:
      aws:cdk:path: DiamondfinishesBackendStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  DiamondFinishesAPIEndpointB929CA34:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: DiamondFinishesAPI2DEAC26E
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: DiamondFinishesAPIDeploymentStageprod6E0DB9B4
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

